services:
  cms:
    image: node:lts
    ports:
      - 4321:4321
      - 4001:4001
    working_dir: /app
    # Startet Tina CMS und Astro im Entwicklungsmodus
    command: sh -c "corepack enable && pnpm install && pnpm run dev"
    env_file:
      - .env
    volumes:
      - ./:/app
